haberler/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = "haberler"

urlpatterns = [
    path('son-haberler', last_news, name="sonhaberler"),
    path('addnews', addnews, name="addnews"),
    path('<slug:slug>', news_list, name="news_list"),
    path('detay/<slug:slug>', news_detail, name="news_detail"),


]

news/urls.py
from django.contrib import admin
from django.urls import path
from home.views import home_view, search_view, takimimiz, author_detail, tags_filter, notfoundpage, login_view, logout,log_password,log_settings,test_page
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name="home_view"),
    path('test',test_page , name="test_page"),
    path('haberler/', include("haberler.urls")),
    path('arama/', search_view, name="search_view"),
    path('takimimiz', takimimiz, name="takimimiz"),
    path('yazarlar/<slug:slug>', author_detail, name="author_detail"),
    path('tags/<slug:slug>', tags_filter, name="tags"),
    path('sayfa-bulunamadi', notfoundpage, name="notfoundpage"),
    path('chaining/', include('smart_selects.urls')),
    # giris & cikis
    path('giris', login_view, name='login'),
    path('cikis', logout, name='logout'),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('settings/', log_settings, name='settings'),
    path('settings/password/', log_password, name='password'),
    # mağaza
    path('magaza/', include("shop.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/site/parts/index/left_trends_index.html
{% load thumbnail %}
<div class="mvp-feat1-mid-wrap left relative">
    <h3 class="mvp-feat1-pop-head"><span class="mvp-feat1-pop-head">Trending</span></h3>
    <div class="mvp-feat1-pop-wrap left relative">
        {% if trend_news %}
            {% for t in trend_news %}
                <a href="{% url 'haberler:news_detail' t.slug %}" rel="bookmark">
                    <div class="mvp-feat1-pop-cont left relative">
                        <div class="mvp-feat1-pop-img left relative">
                            {% thumbnail t.image "400x240" crop="center" as im %}
                                <img width="{{ im.width }}" height="{{ im.height }}"
                                     src="{{ im.url }}"
                                     class="mvp-reg-img wp-post-image" alt="{{ t.title }}"
                                     srcset="{{ im.url }}"
                                     sizes="(max-width: {{ im.width }}) 100vw, {{ im.width }}">
                            {% endthumbnail %}
                            {% thumbnail t.image "80x80" crop="center" as im %}
                                <img width="{{ im.width }}" height="{{ im.height }}"
                                     src="{{ im.url }}"
                                     class="mvp-mob-img wp-post-image" alt="{{ t.title }}"
                                     srcset="{{ im.url }}"
                                     sizes="(max-width: {{ im.width }}) 100vw, {{ im.width }}">
                            {% endthumbnail %}
                            {% if t.video_url != "0" %}
                                <div class="mvp-vid-box-wrap mvp-vid-box-mid mvp-vid-marg">
                                    <i class="fa fa-2 fa-play" aria-hidden="true"></i>
                                </div>
                            {% endif %}
                        </div><!--mvp-feat1-pop-img-->
                        <div class="mvp-feat1-pop-text left relative">
                            <div class="mvp-cat-date-wrap left relative">
                                <span class="mvp-cd-cat left relative">{{ t.category__title }}</span><span
                                    class="mvp-cd-date left relative">{{ t.date | timesince }}</span>
                            </div><!--mvp-cat-date-wrap-->
                            <h2>{{ t.title }}</h2>
                        </div><!--mvp-feat1-pop-text-->
                    </div><!--mvp-feat1-pop-cont-->
                </a>
            {% endfor %}
        {% endif %}

    </div><!--mvp-feat1-pop-wrap-->
</div>

templates/site/parts/index/section_four.html
{% load thumbnail %}
{% load menu %}
{% if news|get_news:category.2.id|length >= 4 %}
    {% with news|get_news:category.2.id as snews %}
        <section id="mvp_home_feat1_widget-4" class="mvp-widget-home left relative mvp_home_feat1_widget">
            <div class="mvp-main-box">
                <div class="mvp-widget-home-head"><a href="{% url 'haberler:news_list' snews.0.category__slug %}"><h4 class="mvp-widget-home-title"><span
                        class="mvp-widget-home-title">{{ snews.0.category__title }}</span></h4></a></div>
                <div class="mvp-widget-feat1-wrap left relative">
                    <div class="mvp-widget-feat1-cont left relative">
                        {% for item in snews %}
                            {% if forloop.counter <= 2 %}
                                <a href="{% url 'haberler:news_detail' item.slug %}" rel="bookmark">
                                    <div class="mvp-widget-feat1-top-story left relative">
                                        <div class="mvp-widget-feat1-top-img left relative">
                                            {% thumbnail item.image "590x354" crop="center" as im %}
                                                <img width="{{ im.width }}"
                                                     height="{{ im.height }}"
                                                     src="{{ im.url }}"
                                                     class="mvp-reg-img lazy wp-post-image"
                                                     alt="{{ item.title }}"
                                                     srcset="{{ im.url }}"
                                                     sizes="(max-width: 400px) 100vw, 400px">
                                            {% endthumbnail %}
                                            {% thumbnail item.image "400x240" crop="center" as im %}
                                                <img width="{{ im.width }}" height="{{ im.height }}"
                                                     src="{{ im.url }}"
                                                     class="mvp-mob-img wp-post-image" alt="{{ t.title }}"
                                                     srcset="{{ im.url }}"
                                                     sizes="(max-width: {{ im.width }}) 100vw, {{ im.width }}">
                                            {% endthumbnail %}
                                        </div><!--mvp-widget-feat1-top-img-->
                                        <div class="mvp-widget-feat1-top-text left relative">
                                            <div class="mvp-cat-date-wrap left relative">
                                                <span class="mvp-cd-cat left relative">{{ item.category__title }}</span><span
                                                    class="mvp-cd-date left relative">{{ item.date | timesince }} önce</span>
                                            </div><!--mvp-cat-date-wrap-->
                                            <h2>{{ item.title }}</h2>
                                        </div><!--mvp-widget-feat1-top-text-->
                                    </div><!--mvp-widget-feat1-top-story-->
                                </a>
                            {% endif %}
                        {% endfor %}
                    </div><!--mvp-widget-feat1-cont-->
                    <div class="mvp-widget-feat1-cont left relative">
                        {% for item in snews %}
                            {% if forloop.counter > 2 and forloop.counter <= 6 %}
                                <a href="{% url 'haberler:news_detail' item.slug %}" rel="bookmark">
                                    <div class="mvp-widget-feat1-bot-story left relative">
                                        <div class="mvp-widget-feat1-bot-img left relative">
                                            {% thumbnail item.image "400x240" crop="center" as im %}
                                                <img width="{{ im.width }}"
                                                     height="{{ im.height }}"
                                                     src="{{ im.url }}"
                                                     class="mvp-reg-img lazy wp-post-image"
                                                     alt="{{ item.title }}"
                                                     srcset="{{ im.url }}"
                                                     sizes="(max-width: 400px) 100vw, 400px">
                                            {% endthumbnail %}
                                            {% thumbnail item.image "80x80" crop="center" as im %}
                                                <img width="{{ im.width }}" height="{{ im.height }}"
                                                     src="{{ im.url }}"
                                                     class="mvp-mob-img wp-post-image" alt="{{ t.title }}"
                                                     srcset="{{ im.url }}"
                                                     sizes="(max-width: {{ im.width }}) 100vw, {{ im.width }}">
                                            {% endthumbnail %}
                                        </div><!--mvp-widget-feat1-bot-img-->
                                        <div class="mvp-widget-feat1-bot-text left relative">
                                            <div class="mvp-cat-date-wrap left relative">
                                                <span class="mvp-cd-cat left relative">{{ item.category__title }}</span><span
                                                    class="mvp-cd-date left relative">{{ item.date | timesince }} önce</span>
                                            </div><!--mvp-cat-date-wrap-->
                                            <h2>{{ item.title }}</h2>
                                        </div><!--mvp-widget-feat1-bot-text-->
                                    </div><!--mvp-widget-feat1-bot-story-->
                                </a>
                            {% endif %}
                        {% endfor %}
                    </div><!--mvp-widget-feat1-cont-->
                </div><!--mvp-widget-feat1-wrap-->

            </div>
        </section>
    {% endwith %}
    {% else %}
    <h1>[Section4]için yeterli haber yok </h1>
{% endif %}

templates/site/parts/index/section_tree.html
{% load thumbnail %}
{% load menu %}
{% if news|get_news:category.1.id|length >= 3 %}
    {% with news|get_news:category.1.id as snews %}
        <section id="mvp_home_feat2_widget-4" class="mvp-widget-home left relative mvp_home_feat2_widget">
        <div class="mvp-main-box">
            <div class="mvp-widget-home-head"><a href="{% url 'haberler:news_list' snews.0.category__slug %}"><h4 class="mvp-widget-home-title"><span
                    class="mvp-widget-home-title">{{ snews.0.category__title }}</span></h4></a></div>
            <div class="mvp-widget-feat2-wrap left relative">
                <div class="mvp-widget-feat2-out left relative">
                    <div class="mvp-widget-feat2-in">
                        <div class="mvp-widget-feat2-main left relative">
                            <div class="mvp-widget-feat2-left left relative mvp-widget-feat2-left-alt">
                                <a href="{% url 'haberler:news_detail' snews.0.slug %}" rel="bookmark">
                                    <div class="mvp-widget-feat2-left-cont left relative">
                                        <div class="mvp-feat1-feat-img left relative">
                                            {% thumbnail snews.0.image "560x600" crop="center" as im %}
                                                <img width="{{ im.width }}"
                                                     height="{{ im.height }}"
                                                     src="{{ im.url }}"
                                                     class="attachment-mvp-port-thumb size-mvp-port-thumb wp-post-image"
                                                     alt="{{ item.title }}"
                                                     srcset="{{ im.url }}"
                                                     sizes="(max-width: {{ im.width }}) 100vw, {{ im.width }}px">
                                            {% endthumbnail %}</div><!--mvp-feat1-feat-img-->
                                        <div class="mvp-feat1-feat-text left relative">
                                            <div class="mvp-cat-date-wrap left relative">
                                                <span class="mvp-cd-cat left relative">{{ snews.0.category__title }}</span><span
                                                    class="mvp-cd-date left relative">{{ snews.0.date |timesince }} önce</span>
                                            </div><!--mvp-cat-date-wrap-->
                                            <h2>{{ snews.0.title }}</h2>
                                            <p>{{ snews.0.spot }}</p>
                                        </div><!--mvp-feat1-feat-text-->
                                    </div><!--mvp-widget-feat2-left-cont-->
                                </a>
                            </div><!--mvp-widget-feat2-left-->
                            <div class="mvp-widget-feat2-right left relative">
                                <a href="{% url 'haberler:news_detail' snews.1.slug %}" rel="bookmark">
                                    <div class="mvp-widget-feat2-right-cont left relative">
                                        <div class="mvp-widget-feat2-right-img left relative">
                                            {% thumbnail snews.1.image "400x240" crop="center" as im %}
                                                <img width="{{ im.width }}"
                                                     height="{{ im.height }}"
                                                     src="{{ im.url }}"
                                                     class="mvp-reg-img lazy wp-post-image"
                                                     alt="{{ item.title }}"
                                                     srcset="{{ im.url }}"
                                                     sizes="(max-width: {{ im.width }}) 100vw, {{ im.width }}px">
                                            {% endthumbnail %}
                                            {% thumbnail snews.1.image "400x240" crop="center" as im %}
                                                <img width="{{ im.width }}" height="{{ im.height }}"
                                                     src="{{ im.url }}"
                                                     class="mvp-mob-img wp-post-image" alt="{{ snews.1.title }}"
                                                     srcset="{{ im.url }}"
                                                     sizes="(max-width: {{ im.width }}) 100vw, {{ im.width }}">
                                            {% endthumbnail %}
                                        </div><!--mvp-widget-feat2-right-img-->
                                        <div class="mvp-widget-feat2-right-text left relative">
                                            <div class="mvp-cat-date-wrap left relative">
                                                <span class="mvp-cd-cat left relative">{{ snews.1.category__title }}</span><span
                                                    class="mvp-cd-date left relative">{{ snews.1.date |timesince }} önce</span>
                                            </div><!--mvp-cat-date-wrap-->
                                            <h2>{{ snews.1.title }}</h2>
                                        </div><!--mvp-widget-feat2-right-text-->
                                    </div><!--mvp-widget-feat2-right-cont-->
                                </a>
                                <a href="{% url 'haberler:news_detail' snews.2.slug %}" rel="bookmark">
                                    <div class="mvp-widget-feat2-right-cont left relative">
                                        <div class="mvp-widget-feat2-right-img left relative">
                                            {% thumbnail snews.2.image "400x240" crop="center" as im %}
                                                <img width="{{ im.width }}"
                                                     height="{{ im.height }}"
                                                     src="{{ im.url }}"
                                                     class="mvp-reg-img lazy wp-post-image"
                                                     alt="{{ item.title }}"
                                                     srcset="{{ im.url }}"
                                                     sizes="(max-width: {{ im.width }}) 100vw, {{ im.width }}px">
                                            {% endthumbnail %}
                                            {% thumbnail snews.2.image "400x240" crop="center" as im %}
                                                <img width="{{ im.width }}" height="{{ im.height }}"
                                                     src="{{ im.url }}"
                                                     class="mvp-mob-img wp-post-image" alt="{{ snews.2.title }}"
                                                     srcset="{{ im.url }}"
                                                     sizes="(max-width: {{ im.width }}) 100vw, {{ im.width }}">
                                            {% endthumbnail %}
                                        </div><!--mvp-widget-feat2-right-img-->
                                        <div class="mvp-widget-feat2-right-text left relative">
                                            <div class="mvp-cat-date-wrap left relative">
                                                <span class="mvp-cd-cat left relative">{{ snews.2.category__title }}</span><span
                                                    class="mvp-cd-date left relative">{{ snews.2.date |timesince }} önce</span>
                                            </div><!--mvp-cat-date-wrap-->
                                            <h2>{{ snews.2.title }}</h2>
                                        </div><!--mvp-widget-feat2-right-text-->
                                    </div><!--mvp-widget-feat2-right-cont-->
                                </a>
                            </div><!--mvp-widget-feat2-right-->
                        </div><!--mvp-widget-feat2-main-->
                    </div><!--mvp-widget-feat2-in-->
                    <div class="mvp-widget-feat2-side left relative">
{#                        <div class="mvp-widget-feat2-side-ad left relative">#}
{#                            <span class="mvp-ad-label">Advertisement</span>#}
{#                            <img src="http://www.mvpthemes.com/zoxsnews/wp-content/uploads/2017/07/zox300.png">#}
{#                        </div><!--mvp-widget-feat2-side-ad-->#}
                        <div class="mvp-widget-feat2-side-list left relative">
                            <div class="mvp-feat1-list left relative">
                                {% for n in snews %}
                                    {% if forloop.counter > 3 and forloop.counter <= 6 %}
                                        <a href="{% url 'haberler:news_detail' n.slug %}"
                                           rel="bookmark">
                                            <div class="mvp-feat1-list-cont left relative">
                                                <div class="mvp-feat1-list-out relative">
                                                    <div class="mvp-feat1-list-img left relative">
                                                        {% thumbnail n.image "80x80" crop="center" as im %}
                                                            <img width="{{ im.width }}" height="{{ im.height }}"
                                                                 src="{{ im.url }}"
                                                                 class="attachment-mvp-small-thumb size-mvp-small-thumb wp-post-image"
                                                                 srcset="{{ im.url }}"
                                                                 sizes="(max-width: {{ im.width }}) 100vw, {{ im.width }}px">
                                                        {% endthumbnail %}</div>
                                                    <!--mvp-feat1-list-img-->
                                                    <div class="mvp-feat1-list-in">
                                                        <div class="mvp-feat1-list-text">
                                                            <div class="mvp-cat-date-wrap left relative">
                                                                <span class="mvp-cd-cat left relative">{{ n.category__title }}</span><span
                                                                    class="mvp-cd-date left relative">{{ n.date | timesince }}</span>
                                                            </div><!--mvp-cat-date-wrap-->
                                                            <h2>{{ n.title }}</h2>
                                                        </div><!--mvp-feat1-list-text-->
                                                    </div><!--mvp-feat1-list-in-->
                                                </div><!--mvp-feat1-list-out-->
                                            </div><!--mvp-feat1-list-cont-->
                                        </a>
                                    {% endif %}

                                {% endfor %}
                            </div><!--mvp-feat1-list-->
                            <a href="{% url 'haberler:news_list' snews.0.category__slug %}">
                                <div class="mvp-widget-feat2-side-more-but left relative">
                                    <span class="mvp-widget-feat2-side-more">{{ snews.0.category__title }}</span><i
                                        class="fa fa-long-arrow-right" aria-hidden="true"></i>
                                </div><!--mvp-widget-feat2-side-more-but-->
                            </a>
                        </div><!--mvp-widget-feat2-side-list-->
                    </div><!--mvp-widget-feat2-side-->
                </div><!--mvp-widget-feat2-out-->
            </div><!--mvp-widget-feat2-wrap-->

        </div>
    </section>
    {% endwith %}
    {% else %}
    <hr>
    <p>[section3]bu section için henüz 6 haber yok şuan :{{ news|get_news:"2,5"|length }}</p>
{% endif %}

templates/site/parts/index/section_two_video.html
{% load menu %}
{% load thumbnail %}
{% if news|get_news_video:4|length >= 4 %}
 {% with news|get_news_video:4 as snews %}
    <section class="mvp-widget-home left relative">
        <div class="mvp-widget-dark-wrap left relative">
            <div class="mvp-main-box">
                <div class="mvp-widget-home-head">
                    <a href="{% url 'haberler:news_list' snews.0.category__slug %}"><h4 class="mvp-widget-home-title">
                        <span class="mvp-widget-home-title">Videos</span></h4></a>
                </div><!--mvp-widget-home-head-->
                <div class="mvp-widget-dark-main left relative">
                    {% for item in snews %}
                        {% if forloop.counter == 1 %}
                            <div class="mvp-widget-dark-left left relative">
                                <a href="{% url 'haberler:news_detail' item.slug %}" rel="bookmark">
                                    <div class="mvp-widget-dark-feat left relative">
                                        <div class="mvp-widget-dark-feat-img left relative">
                                            {% thumbnail item.image "1000x600" crop="center" as im %}
                                                <img width="{{ im.width }}"
                                                     height="{{ im.height }}"
                                                     src="{{ im.url }}"
                                                     class="mvp-reg-img lazy wp-post-image"
                                                     alt="{{ item.title }}"
                                                     srcset="{{ im.url }}"
                                                     sizes="(max-width: {{ im.width }}) 100vw, {{ im.width }}px">
                                            {% endthumbnail %}
                                            {% thumbnail item.image "400x240" crop="center" as im %}
                                                <img width="{{ im.width }}"
                                                     height="{{ im.height }}"
                                                     src="{{ im.url }}"
                                                     class="mvp-mob-img lazy wp-post-image"
                                                     alt="{{ item.title }}"
                                                     srcset="{{ im.url }}"
                                                     sizes="(max-width: {{ im.width }}) 100vw, {{ im.width }}px">
                                            {% endthumbnail %}
                                            <div class="mvp-vid-box-wrap mvp-vid-marg">
                                                <i class="fa fa-2 fa-play" aria-hidden="true"></i>
                                            </div><!--mvp-vid-box-wrap-->
                                        </div><!--mvp-widget-dark-feat-img-->
                                        <div class="mvp-widget-dark-feat-text left relative">
                                            <div class="mvp-cat-date-wrap left relative">
                                                <span class="mvp-cd-cat left relative">{{ item.category__title }}</span><span
                                                    class="mvp-cd-date left relative">{{ item.date |timesince }} önce</span>
                                            </div><!--mvp-cat-date-wrap-->
                                            <h2>{{ item.title }}</h2>
                                        </div><!--mvp-widget-dark-feat-text-->
                                    </div><!--mvp-widget-dark-feat-->
                                </a>
                            </div>
                        {% endif %}
                    {% endfor %}

                    <!--mvp-widget-dark-left-->
                    <div class="mvp-widget-dark-right left relative">
                        {% for item in snews %}
                            {% if forloop.counter > 1 and forloop.counter <= 5 %}
                                <a href="{% url 'haberler:news_detail' item.slug %}" rel="bookmark">
                                    <div class="mvp-widget-dark-sub left relative">
                                        <div class="mvp-widget-dark-sub-out right relative">
                                            <div class="mvp-widget-dark-sub-img left relative">
                                                {% thumbnail item.image "400x240" crop="center" as im %}
                                                    <img width="{{ im.width }}"
                                                         height="{{ im.height }}"
                                                         src="{{ im.url }}"
                                                         class="mvp-reg-img lazy wp-post-image"
                                                         alt="{{ item.title }}"
                                                         srcset="{{ im.url }}"
                                                         sizes="(max-width: {{ im.width }}) 100vw, {{ im.width }}px">
                                                {% endthumbnail %}
                                                {% thumbnail item.image "80x80" crop="center" as im %}
                                                    <img width="{{ im.width }}"
                                                         height="{{ im.height }}"
                                                         src="{{ im.url }}"
                                                         class="mvp-mob-img lazy wp-post-image"
                                                         alt="{{ item.title }}"
                                                         srcset="{{ im.url }}"
                                                         sizes="(max-width: {{ im.width }}) 100vw, {{ im.width }}px">
                                                {% endthumbnail %}
                                                <div class="mvp-vid-box-wrap mvp-vid-box-small mvp-vid-marg-small">
                                                    <i class="fa fa-2 fa-play" aria-hidden="true"></i>
                                                </div><!--mvp-vid-box-wrap-->
                                            </div><!--mvp-widget-dark-sub-img-->
                                            <div class="mvp-widget-dark-sub-in">
                                                <div class="mvp-widget-dark-sub-text left relative">
                                                    <div class="mvp-cat-date-wrap left relative">
                                                        <span class="mvp-cd-cat left relative">{{ item.category__title }}</span><span
                                                            class="mvp-cd-date left relative">{{ item.date |timesince }} önce</span>
                                                    </div><!--mvp-cat-date-wrap-->
                                                    <h2>{{ item.title }}</h2>
                                                </div><!--mvp-widget-dark-sub-text-->
                                            </div><!--mvp-widget-dark-sub-in-->
                                        </div><!--mvp-widget-dark-sub-out-->
                                    </div><!--mvp-widget-dark-sub-->
                                </a>
                            {% endif %}
                        {% endfor %}
                    </div><!--mvp-widget-dark-right-->
                </div><!--mvp-widget-dark-main-->
            </div><!--mvp-main-box-->
        </div><!--mvp-widget-dark-wrap-->
    </section>
{% endwith %}
{% else %}
    [section2]video sekmesi için yeterli(5) haber bulunamadı şuan : {{ news|get_news_video:4|length }}
{% endif %}